#!/usr/bin/env bash
# Install Nginx with the following:
#	 listens on port 80
#	 Returns a page containing "Hello World!" with Curl GET Request
#sudo apt-get update
#sudo apt-get install -y nginx
#mkdir /etc/nginx/html
#touch /etc/nginx/html/index.html
#echo "Hello World!" > /etc/nginx/html/index.html
#printf %s "server {
#    listen      80 default_server;
#     listen      [::]:80 default_server;
#     root        /etc/nginx/html;
#     index       index.html index.htm;
#}
#" > /etc/nginx/sites-available/default
# setup custom HTML file
sudo apt-get update
sudo apt-get -y install nginx

sudo service nginx start
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R 755 /var/www

sudo echo -e "Hello World!" | dd status=none of=/var/www/html/index.html
#sudo chmod 666 /var/www/html/index.nginx-debian.html
#sudo chmod 666 /usr/share/nginx/html/index.html
#echo "Hello World!" > /var/www/html/index.nginx-debian.html
#echo "Hello World!" > /usr/share/nginx/html/index.html


# start Nginx
sudo service nginx restart
